### ISSUE TITLE
01-US-CapstoneProject-Profan 

### ISSUE THREAD

**Issue by Elgin-Schultz** [Elgin-Schultz/capstone-project#1]
## Value Proposition

**As a user** ... I would like to get an overview of the sites listed in this app.

**I need** ... to view existing sites and their approximate location.

**to be able to** ... decide for which site I want to get more information.

## Description
![Profan-FirstUSa](https://user-images.githubusercontent.com/115506885/206730850-20d58fde-193a-40a6-a847-03d00d302a63.png)

## Acceptance Criteria

- [ ] see all sites with icons
- [ ] in a topology order
- [ ] map as background image

## Tasks

(for developers team)

- [ ] list all sites
- [ ] put them in a grid
- [ ] use background image

**Comment by BrainCodeJockey** [comment]
ich würde maybe weglassen

**Comment by ufelgen** [comment]
Hey Elgin, ziemlich cool! ich frag mich nur gerade, ob es sinnvoll ist, da "maybes" reinzuschreiben.... vielleicht ist die US1 ohne maybes und die maybes packst du in US2? und hast du hier schon Daten drin, die angezeigt werden? Die Ansicht mit dem Telefon ist total schick :) 

PS ah ja, was Alex sagt :)

**Comment by Elgin-Schultz** [comment]
Wollte mir das ein wenig offen lassen, vielleicht schreibe ich besser Variante a, b. Dann darf der Product Owner entscheiden, was ihm besser gefällt! ;)

**Comment by julialoeschel** [comment]
Hex Elgin, sieht gut aus. 

bei "I need ... to see a kind of list of all sites in a topology." würde ich etwas konkreter formulieren...
"I need ... to view existing sites and their location" oder so ähnlich vielleicht? 

ansonsten supi
