### ISSUE TITLE
04-US-CapstoneProject-Profan

### ISSUE THREAD

**Issue by Elgin-Schultz** [Elgin-Schultz/capstone-project#10]
## Value Proposition

**As a** ... as a historic interested person that uses the App I want to know about the credits.

**I need** ... to go to the credit section,

**to be able to** ... get the wanted information

## Description

![Profan-4](https://user-images.githubusercontent.com/115506885/208647791-11051492-39f9-4e84-8cfd-f065b5398be0.png)

## Acceptance Criteria

- [ ] credits are displayed on page
- [ ] credits for each picture, document are shown, i. e. the sources where the documents, pictures are from
- [ ] possibility to go back to the page where the sites are listed

## Tasks

(for developers team)

- [ ] implement a page for credits
- [ ] route to credite page
- [ ] add button to link back to sites list

**Comment by altanguellue** [comment]
Hi Elgin :) Kurze Anmerkungen zu deiner US:

1. Bzgl. der Value Proposition bin ich mir nicht sicher, ob du die erste Zeile so aus definieren musst. Laut Template heißt es ja "As a user/author etc. Vielleicht kannst du das so anpassen:

"As a (historic interested) user
I need a credit section
to be able to get all the app information."

2. Vielleicht solltest du in deinem Scribble die Credits etwas detaillierter beschreiben. Zumindest erschließt sich mir noch nicht so ganz, was genau du mit Credits meinst :) In den Acceptance Criteria steht dazu noch, dass Bilder gezeigt werden und man zurück navigieren kann. Vielleicht könntest du dazu auch noch in deinem Scribble einfach ein Rechteck oder so reinpacken, welches eben ein img darstellen soll.

**Comment by Elgin-Schultz** [comment]
Hallo Altan,
vielen Dank für deine Anmerkungen!
-"historic interested person that uses the App" war mal ein Wunsch von Julia
-Credits sind die Bildnachweise, das heißt auf dieser Seite ist nur Text, die Quellen, wo die Bilder herkommen, aber keine Bilder selbst. Ich formulieren nochmal um in der US...
