### ISSUE TITLE
05-US-CapstoneProject-Profan

### ISSUE THREAD

**Issue by Elgin-Schultz** [Elgin-Schultz/capstone-project#11]
## Value Proposition

**As a** ... as a user I want to know about the owner.

**I need** ... to go to the imprint section,

**to be able to** ... get the wanted information

## Description

![Profan-5](https://user-images.githubusercontent.com/115506885/208649227-2395d549-e1c6-4d96-b182-d82e146ca1c2.png)

## Acceptance Criteria

- [ ] imprint is displayed on page
- [ ] possibility to go back to the page where the sites are listed

## Tasks

(for developers team)

- [ ] implement a page for imprint
- [ ] route to imprint page
- [ ] add button to link back to sites list

**Comment by altanguellue** [comment]
1. Zur Value Proposition eine kleine Anmerkung bzw. Änderungsvorschlag:

"As a user
I need an imprint section,
to be able to get the information about the owner."

2.  possibility to go back to the page where the sites are listed -> Soll das durch ein Button möglich gemacht werden? Diesen könntest du dann auch in den Scribble skizzieren :)

**Comment by Elgin-Schultz** [comment]
Hallo Altan, tausen Dank für deine Anmerkungen! Der pinkfarbene Punkt in der Mittte unten soll mein Button sein ...  :)
