### ISSUE TITLE
07-US-Add Data-CapstoneProject-Profan 

### ISSUE THREAD

**Issue by Elgin-Schultz** [Elgin-Schultz/capstone-project#15]
## Value Proposition

**As a** ...  user I want to see more than just one location,

**to be able to** ... get more information.

## Description

Add more data in the same structure:
slug: "1",
    coordinates: [53.577587, 9.991238],
    adress: ["Oberstraße 120"],
    information:
      "Dieses Gebäude in der Oberstraße 120 war das dritte Bethaus des Israelitischen Tempelvereins, der jüdischen Reformbewegung Hamburgs, die am 11.12.1817 gegründet wurde. Ihr alter Tempel in der Poolstraße war zu klein geworden und die meisten Gemeindemitglieder mittlerweile auch nicht mehr in der Neustadt ansässig. Daher wurde 1929 ein Wettbewerb für das Grundstück in Rotherbaum ausgerufen. Mit dem Bau beauftragt wurden dann die Gewinner des ersten und dritten Platzes: Felix Ascher und Robert Friedmann, die ihre beiden Entwürfe im Bauhausstil zu einem neuen zusammenführten. Die Grundsteinlegung fand am 19.10.1930 statt. Eingeweiht wurde der neue Tempel am 30.08.1930. Im großen Hauptraum fasste er etwa 1 200 Besucher und entsprach damit dem bis dato größten jüdischen Bethaus der Stadt: der Bornplatzsynagoge. In der Pogromnacht des 09.11.1938 wurde die Inneneinrichtung zerstört, äußerlich war das Gebäude jedoch kaum beschädigt. Angeblich wegen der Nähe des Polizeireviers in direkter Nachbarschaft, eine verbrannte Synagoge gleich nebenan wäre zu offensichtlich gewesen? Am 28.11.1940 kam es dann zum Zwangsverkauf an die Stadt, lediglich der Grundstückspreis wurde der jüdischen Gemeinde erstattet, die Baukosten von rund und 560 000 Reichsmark nicht berücksichtigt.Hamburg hatte das Gebäude als Sitz für Dienststellen vorgesehen, etwa für das neu einzurichtende Kolonialamt, die Reichsstelle für Bodenforschung oder das Institut für Leibeserziehung. Genutzt wurde es allerdings als Verlagsgebäude, Getreidelager und Kino. 1946 vermietete die Stadt den Bau an den NWDR, der es 1950 zum Großen Sendesaal umbaute. 1953 kaufte ihn der Radiosender der Jewish Trust Corporation ab. Noch heute wird es als Rolf-Liebermann-Tonstudio des NDR genutzt. 1982 wurde der ehemalige Tempel unter Denkmalschutz gestellt und seit 1983 verweist das Mahnmal der Künstlerin Doris Waschk-Balz auf seine traurige Geschichte.",
    document: "/images/1-311-2_IV_Finanzdeputation_IV_DV_I_B2g_V _1_9.png",
    documentSource: [
      "Akte der Kämmerei, 1940, Staatsarchiv Hamburg, 113-5, E IV DIV B2g V B1",
    ],
    quote:
      "„..., daß dieser Raum geweiht werde, daß jene Wandlung vor sich gehe, die aus dem Profanen ein Heiliges schafft, kurz, daß das Wunder sich vollziehe, daß Eisen und Stein und Holz und Wand und Leuchter und Thorarollen mit den lebendigen Menschenseelen zu einem Chor der Andacht zusammenklingen.“",
    quoteSource:
      "Bruno Italiener: Ansprache zur Einweihung des neuen Tempels, 30.08.1931",
    currentPicture: ["/images/1_MG_1448.jpg", "/images/1_MG_1271.jpg"],
    ancientPicture: [
      "/images/1-141-16_5-600.png",
      "/images/1-JudentumundreligioeseReform0003.png",
      "/images/1-Festschrift0002.png",
      "/images/1-Bau00260.png",
      "/images/1-Bau00259.png",
    ],
    ancientCaption: [
      "Der neue Tempel in der Oberstraße, ~1937",
      "Der Hauptraum, ~1931",
      "Der Hauptraum, ~1931",
      "Ausweichbetrieb des Hamburger Fremdenblatts, ~1941",
      "Ausweichbetrieb des Hamburger Fremdenblatts, ~1941",
    ],
    creditsCaption: "Abbildungsnachweis",
    credits: [
      "-Staatsarchiv Hamburg, Plankammer 720-1 141-16=5/600",
      "-Museum für Hamburgische Geschichte/Foto: Gustav Wolfes",
      "-Scan: Italiener, Bruno: Festschrift zum hundertzwanzigjährigem Bestehen des Israelitischen Tempels in Hamburg, Hamburg 1937/Foto: Erich Kastan",
      "-Institut für die Geschichte der deutschen Juden, BAU00260/Foto: Fotoarchiv Völkerhof",
      "-Institut für die Geschichte der deutschen Juden, BAU00259/Foto: Fotoarchiv Völkerhof",
    ],

## Acceptance Criteria

- [ ] data of all sites is shown

## Tasks

(for developers team)

- [ ] put all data in the array of strings
- [ ] use the same structure as for slug 1

**Comment by AntjeWalter** [comment]
Wow, I did not expect that description :D Not sure, if this is necessary but I guess it won't hurt.
Also, in your Value Proposition at the top you only need the "I want" OR "I need". So the first line would just be "As a user" and then you have "I need" or "I want" and then in the third line you have "to be able to". So maybe you could put your info in one line or decide for one of your statements :) 
I would also add a more descriptive headline for your US that summarizes you goal with this US.
But other than that, this US seems doable and you will rock it ;)
