### ISSUE TITLE
08-US-CapstoneProject-Profan

### ISSUE THREAD

**Issue by Elgin-Schultz** [Elgin-Schultz/capstone-project#16]
## Value Proposition

**As a** ...  user I want to see pictures of more than just one location.

**I need** ... get access to the photos of more sites,

**to be able to** ... get the wanted information.

## Description

-revise the images that they all are PNGs, have 72 dpi, RGB or Greyscale mode, similar sizes, ...

## Acceptance Criteria

- [ ] pictures are shown
- [ ] PNG, 72 dpi, RGB or Greyscale mode

## Tasks

(for developers team)

- [ ] rework images
- [ ] upload the pictures to public/images

**Comment by AntjeWalter** [comment]
For the acceptance criteria I would add that they have the same format because that seems to be the point of this US :)
Otherwise, nice!

**Comment by Elgin-Schultz** [comment]
Oh yes!
