### ISSUE TITLE
02-US-CapstoneProject-Profan 

### ISSUE THREAD

**Issue by Elgin-Schultz** [Elgin-Schultz/capstone-project#2]
## Value Proposition

**As a** ... as a historic interested person that uses the App I want to know more about the individual sites.

**I need** ... to click the site buttons to get to their own pages,

**to be able to** ... see more information

## Description

![Profan-FirstUSb](https://user-images.githubusercontent.com/115506885/207099374-45118d5e-794c-49c8-9e3b-adf97d7e23ec.png)
![Profan-Second-1-1](https://user-images.githubusercontent.com/115506885/207098860-fbc4c7fe-9ed0-41cd-a478-0d8934ed2c96.png)
![Profan-Second-2-1](https://user-images.githubusercontent.com/115506885/207101744-e8f58c4c-f128-4202-b0e5-555697cfaf6d.png)

...

## Acceptance Criteria

- [ ] render seven dynamic landingpages from data
- [ ] render all information of each site, use scroll function
- [ ] add homepage button

## Tasks

(for developers team)

- [ ] implement a page for each site
- [ ] add button to link back to homepage

**Comment by onebarloop** [comment]
How does the navigation work? Forward/backward buttons or a menu?

**Comment by julialoeschel** [comment]
Hello :) 

- As a ... user ! 
  oder, "as a historic interested person that uses the App" :D 
-  render seven different landing pages -> render dynamic Landingpages from Data 
- und die Navigation sollte im Scribble irgendwie auftachen, wenn auch nur angedeutet. 

sonst 👍
