### ISSUE TITLE
03-US-CapstoneProject-Profan

### ISSUE THREAD

**Issue by Elgin-Schultz** [Elgin-Schultz/capstone-project#8]
## Value Proposition

**As a** ...  as a historic interested person that uses the App,
**I want to** ... to get general information about the app and what kind of sites are shown,
**so that** ... I can decide to go to the single sites or not
​

## Description
![Profan-Fourth](https://user-images.githubusercontent.com/115506885/208421385-0568c1e3-50a6-4828-b48f-a47ae314f6aa.png)

## Acceptance Criteria

- [ ] get overview
- [ ] still have the possibility to go to the subpages

      ​

## Tasks

- [ ] render overview text on index.js 
- [ ] links to subpages go after the text

      ​

**Comment by ufelgen** [comment]
Hey Elgin, 
ich würde in der proposition spezifizieren "general information about historic sites featured on the app". Und ich würde noch genauer schreiben, wo was gerendert werden soll. Ich nehme an dein neuer Text mit der general information soll auf die index.js Startseite? Die Links zu den einzelnen Stätten gibt es dort ja schon.

**Comment by Elgin-Schultz** [comment]
Ich danke dir sehr! Habe umformuliert!
